### ISSUE TITLE
bug on rogue assassination

### ISSUE THREAD

**Issue by ncplus0** [AlexFolland/AutoGear#21]
i've tested with version 2021-07-26-release-2

and still have the bug on rogues spec assassination

it keeps replacing weapons from daggers to mace and swords, rogues assassination only use daggers and the spells does not work with other weapons, I've reported this bug several times and still is not fixed yet

**Comment by AlexFolland** [comment]
This is the first report for this I see here, and I see no pull request.  That being said, thanks for reporting this.  I may look into it later today.

What variation of WoW are you using?

**Comment by ncplus0** [comment]
retail, i dint tested yet on classic, but probably the same error
btw the report was on the comments on curse not here, here i think its the 1 time

**Comment by AlexFolland** [comment]
I haven't had the energy to look into this, but please feel free to fork AutoGear, fix it, test the fix, and submit a pull request.  I will review the pull request and merge it if it's fine.

**Comment by ncplus0** [comment]
i think the clue to fix is to create a variable like in line 2651 to detect the spec for assassination and then do like line 2722 and define for both hands, but i have no idea where to set the text

**Comment by AlexFolland** [comment]
I've released a potential fix.  Please test it when you have time and let me know how it goes.

**Comment by AlexFolland** [comment]
I haven't heard back, and I believe my fix worked, so I'm closing this.  Please feel free to reopen it if there is an issue.  Thank you!
