### ISSUE TITLE
[Security] Workflow release.yml is using vulnerable action actions/checkout

### ISSUE THREAD

**Issue by Freakston** [AlexFolland/AutoGear#22]
The workflow release.yml is referencing action actions/checkout using references v1. However this reference is missing the commit [a6747255bd19d7a757dbdda8c654a9f84db19839](https://github.com/actions/checkout/commits/a6747255bd19d7a757dbdda8c654a9f84db19839) which may contain fix to the some vulnerability. 
The vulnerability fix that is missing by actions version could be related to: 
(1) CVE fix 
(2) upgrade of vulnerable dependency 
(3) fix to secret leak and others. 
Please consider to update the reference to the action.

**Comment by AlexFolland** [comment]
Thanks.  Does my change in 614137963b73fee97a7f2c3867fdd7fd5f4e90ab fix this issue?

**Comment by AlexFolland** [comment]
It seems to have no problems, and there's been no response for nearly a month, so I'm closing this.  Thanks again for your report.  Please feel free to comment again if this is issue is still relevant.
