### ISSUE TITLE
Not registering equipment

### ISSUE THREAD

**Issue by flutterJackdash** [AlexFolland/AutoGear#23]
AutoGear doesn't seem to register that I'm holding a weapon (Kul Tiran Fury Spec Warrior) so every time I pick up a new weapon, however junk it may be, AutoGear determines that it is better than nothing, and swaps it out for the green gear I have in there, even if the item it determined to be better was grey. I either have to re-equip manually or run a manual scan on AutoGear, and this is happening constantly. It's the first I've ever run into this though, it has worked perfectly for all my toons.

**Comment by AlexFolland** [comment]
Fury has had its bugs over the years due to Titan's Grip.  We've seen this perticular issue in the past, but we thought we fixed it.  Can you please link me to the wowhead pages for the weapons you want to wield, so someone can investigate?

**Comment by flutterJackdash** [comment]
[Helm-Hewer Greataxe](https://www.wowhead.com/item=122389/bloodsoaked-skullforge-reaver?bonus=0) is the gear I'd been working with, but now I've got [Bloodsoaked Skullforge Reaver](https://www.wowhead.com/item=122389/bloodsoaked-skullforge-reaver?bonus=0) x2 equipped and AutoGear is happier for it. Tried to have it duel wield to begin with, but AutoGear first determined that the Greataxe was the better choice and then it didn't seem to register anything was even equipped.

**Comment by AlexFolland** [comment]
This might be fixed in the latest version which is not yet tagged for release.  Would you mind trying with the latest git master?

**Comment by AlexFolland** [comment]
It's been a few months with no response and I expect that this issue is resolved, so I will close the ticket now.  Please feel free to comment here again requesting to reopen this ticket or open a new ticket if you find any issue.
