### ISSUE TITLE
Wotlk update completely broke the addon

### ISSUE THREAD

**Issue by redhawk1337** [AlexFolland/AutoGear#24]
There are no errors or anything,it just doesn't load on wotlk.

**Comment by AmsTaFFix** [comment]
1. i posted some PRs to resolve that problem
2. you can download mine [addon's fork](https://github.com/AmsTaFFix/AutoGear)

**Comment by AmsTaFFix** [comment]
@AlexFolland 
this issue resolved, could you close it?
