### ISSUE TITLE
Classic Version ? :)

### ISSUE THREAD

**Issue by Dastano** [AlexFolland/AutoGear#3]
Any chance you can create a Classic Version for this? While it works on basic stuff in Classic, I am not sure how Wands are Handled or "Increase Critchance by 1% etc" 

Also in Classic often : Shadow Spell Damge/Frost Spell Damage > Int / Spirit etc.

**Comment by AlexFolland** [comment]
It's classic-compatible, and we think we've fixed most of the issues with classic now.  Please feel free to report any more specific issues in separate reports.  Thanks!
