### ISSUE TITLE
error on LFG

### ISSUE THREAD

**Issue by ncplus0** [AlexFolland/AutoGear#32]
the addon blocks the LFG search

![image](https://user-images.githubusercontent.com/72767232/196003672-eef25b5d-7b42-4399-889f-71fe0d495d1b.png)

25x [ADDON_ACTION_BLOCKED] AddOn 'AutoGear' tried to call the protected function 'Search()'.
[string "@!BugGrabber\BugGrabber.lua"]:519: in function <!BugGrabber\BugGrabber.lua:519>
[string "=[C]"]: in function `Search'
[string "@Blizzard_LookingForGroupUI\Blizzard_LFGFrame.lua"]:534: in function `SendLFMQuery'
[string "@Blizzard_LookingForGroupUI\Blizzard_LFGFrame.lua"]:240: in function `SearchActiveEntry'
[string "@Blizzard_LookingForGroupUI\Blizzard_LFGFrame.lua"]:67: in function `LFGParentFrame_LFMSearchActiveEntry'
[string "@Blizzard_LookingForGroupUI\Blizzard_LFGFrame.lua"]:646: in function <...Ons\Blizzard_LookingForGroupUI\Blizzard_LFGFrame.lua:639>

**Comment by ncplus0** [comment]
this is on lfg clasic wotlk

**Comment by AlexFolland** [comment]
I can't reproduce this.  Maybe something else is tainting the execution chain and AutoGear is being blamed for it.  Can you please try with just AutoGear running temporarily?

**Comment by ncplus0** [comment]
i still have the same problem only with autogear on

**Comment by AlexFolland** [comment]
AutoGear does not call protected function `Search()` in its code.  You can verify this yourself in its code, which is inside `AutoGear.lua`.  I also tried queuing for 3 activities and did not have the issue.  Here's me queued for 3 activities with AutoGear running.

![WoWScrnShot_101522_150554](https://user-images.githubusercontent.com/601517/196009359-4b0cdd02-30ad-4e88-862e-4231f8a6a8e2.jpg)

Please give any more information you can think of, because as it stands right now, I have no way of pursuing a fix for it, since AutoGear does not do this, at least with the latest version.

**Comment by ncplus0** [comment]
just tha addon and before i releted settings and reinstall the latest version
![image](https://user-images.githubusercontent.com/72767232/196009506-466ab821-75c8-4908-9636-3e39499c7d64.png)

then i activate the buggraber it gives the error

26x [ADDON_ACTION_BLOCKED] AddOn 'AutoGear' tried to call the protected function 'Search()'.
[string "@!BugGrabber\BugGrabber.lua"]:519: in function <!BugGrabber\BugGrabber.lua:519>
[string "=[C]"]: in function `Search'
[string "@Blizzard_LookingForGroupUI\Blizzard_LFGFrame.lua"]:534: in function `SendLFMQuery'
[string "@Blizzard_LookingForGroupUI\Blizzard_LFGFrame.lua"]:240: in function `SearchActiveEntry'
[string "@Blizzard_LookingForGroupUI\Blizzard_LFGFrame.lua"]:67: in function `LFGParentFrame_LFMSearchActiveEntry'
[string "@Blizzard_LookingForGroupUI\Blizzard_LFGFrame.lua"]:646: in function <...Ons\Blizzard_LookingForGroupUI\Blizzard_LFGFrame.lua:639>

**Comment by AlexFolland** [comment]
I believe you.  As it doesn't happen here, I have no idea how it could possibly happen to you with only AutoGear loaded.  As far as I understand from the code, and I know the whole code base, there is nothing AutoGear does that could trigger this.  If you get any more information, like information about it only happening on a particular character, I'd be glad to know.  As of right now, I have no way of fixing this, despite my sympathy for the situation.

**Comment by AlexFolland** [comment]
I have an idea, suggested by a kind and helpful user in the WoWUIDev Discord.  Can you please try installing the addon named [TaintLess](https://www.townlong-yak.com/addons/taintless), trying to reproduce the issue again, and reporting back?  If [TaintLess](https://www.townlong-yak.com/addons/taintless) prevents the issue, I will investigate what it's doing and implement a similar solution in AutoGear.

**Comment by ncplus0** [comment]
ive tested in all the chars i have and all of them have the bug, i installed the addon you told me and it worked, now all of them can use the LFG and also does not gives that bug report on the chat, see if you can add that code to your addon so that other people could have the same bug

**Comment by AlexFolland** [comment]
Thanks for letting me know!  I checked `TaintLess.xml`, which is the only code file included in TaintLess, and it says `Permission is hereby granted to distribute unmodified copies of this file.`, meaning I am allowed to include it directly in AutoGear, which should fix it for all users who don't explicitly install TaintLess.  I've done so now and pushed a new release.  Would you mind uninstalling TaintLess and running with just AutoGear to test if my fix worked?

**Comment by ncplus0** [comment]
first i uninstall the addon taintless and tested and it gave the error again in my chars, then i update your adoon and it was working normally, I've tested in my other chars and it looks fine now. it looks like it worked. tks for the work mt8, nice job

**Comment by AlexFolland** [comment]
Great.  Thanks for letting me know!
