### ISSUE TITLE
Retail AutoGear-2022-11-10-release Can't ener options trough command line

### ISSUE THREAD

**Issue by ollyvs** [AlexFolland/AutoGear#39]
Can't ener options trough command line
/ag

1x Interface/AddOns/AutoGear/AutoGear.lua:2144: attempt to call global 'InterfaceOpInterfaceOptionsFrame_OpenToCategory' (a nil value)
[string "@Interface/AddOns/AutoGear/AutoGear.lua"]:2144: in function <Interface/AddOns/AutoGear/AutoGear.lua:2071>
[string "=[C]"]: ?
[string "=[C]"]: ?
[string "=[C]"]: ?
[string "=[C]"]: ?
[string "=[C]"]: ?
[string "=[C]"]: ?
[string "=[C]"]: ?
[string "=[C]"]: ?
[string "=[C]"]: ?
[string "=[C]"]: ?
[string "=[C]"]: ?
...
[string "=[C]"]: ?
[string "=[C]"]: ?
[string "=[C]"]: ?
[string "=[C]"]: ?
[string "=[C]"]: ?
[string "=[C]"]: in function `?'
[string "@Interface/FrameXML/ChatFrame.lua"]:5219: in function `ChatEdit_ParseText'
[string "@Interface/FrameXML/ChatFrame.lua"]:4883: in function `ChatEdit_SendText'
[string "@Interface/FrameXML/ChatFrame.lua"]:4919: in function `ChatEdit_OnEnterPressed'
[string "*ChatFrame.xml:127_OnEnterPressed"]:1: in function <[string "*ChatFrame.xml:127_OnEnterPressed"]:1>

Locals:
msg = ""
(*temporary) = nil
(*temporary) = AutoGearOptionsPanel {
 0 = <userdata>
 name = "AutoGear"
}
(*temporary) = "attempt to call global 'InterfaceOpInterfaceOptionsFrame_OpenToCategory' (a nil value)"
optionsMenu = AutoGearOptionsPanel {
 0 = <userdata>
 name = "AutoGear"
}
shouldPrintHelp = false

**Comment by AlexFolland** [comment]
I've just released a fix in release `2022-11-11-release`.  If you're reading this immediately upon posting this response, the release isn't available yet, but it'll be available in about 10 minutes usually.  When it's available, would you mind checking it?
