### ISSUE TITLE
URGENT! Option to disable "replace of broken gear"

### ISSUE THREAD

**Issue by noelpy** [AlexFolland/AutoGear#44]
Currently: If a gearpiece is broken autogear switches to intact piece from inventory and stuff like this happens:

"AutoGear: [Farshire Shoulderpads of the Prophet] (1.90) was determined to be better than [Daggercap Spaulders of the Bear] (49.12).  Equipping."

Please give us an option to disable the auto-equip for broken gear!

**Comment by noelpy** [comment]
WOTLK Addon Version

**Comment by AlexFolland** [comment]
This is intended behavior to avoid using broken gear.  Broken gear doesn't do anything, so something in your bags that's not broken is better.  When the better gear is repaired, it will be better again and will be equipped.

That being said, options are good.  I'm just not sure I have time to implement it right now.  More urgent is fixing the whole addon for Dragonflight, and I haven't had time to do that either.

In the mean time, disable auto-equipping if you want to leave broken gear on, but that's usually not good.

**Comment by noelpy** [comment]
thank you for the quick reply. im using some kind of 1click auto-selling (grey, greens and some predefined whites) while repairing. thats why i would love an option to just leave that broken piece equipped. but sure in terms of ur addon Retail stuff might be more important (even when im sticked to wotlk and havent touched DF)

**Comment by AlexFolland** [comment]
I've been considering whether implementing this option is worthwhile.  My thoughts:

- Broken gear does nothing, so leaving a broken item equipped while a viable item that's not broken is available to equip is almost always the wrong decision.
- Adding another option that supports an extreme minority of users adds a maintenance cost which does not match the minority of users.

I do value having options, but the cost outweighs the benefit, from my perspective.  Therefore, I have decided that I will not plan to implement a new option just to allow preventing AutoGear from replacing broken gear.  It's possible that I implement one spontaneously in the future, but it does not seem likely.  I would probably accept a pull request that does it if the implementation is simple enough and does not introduce issues.
