### ISSUE TITLE
Using wrong pawn spec

### ISSUE THREAD

**Issue by Hendo72** [AlexFolland/AutoGear#54]
Ran \ag spec:
![image](https://github.com/AlexFolland/AutoGear/assets/39675478/e0b231c3-6f87-4af0-ac3e-da3f5e6ee778)

Clearly, I am not.
![image](https://github.com/AlexFolland/AutoGear/assets/39675478/aacff92d-a755-45ff-b552-40f68d81da4e)

I've had this issue before and was forced to use the settings to make it use the right one.
![image](https://github.com/AlexFolland/AutoGear/assets/39675478/31a0c796-5491-44c2-986c-e53a38498d1b)

It seems I only get this with Druids. I did a reload prior to to taking the screenshots and it said Restoration before switching to Tank after the reload.

**Comment by AlexFolland** [comment]
Do you have any talents?  If so, please show me your current talent trees so I can figure out what's happening here.

**Comment by Hendo72** [comment]
I'm level 8. So, technically, I am 'none'.

**Comment by AlexFolland** [comment]
With no spec to use to determine which Pawn scale to choose, AutoGear found the first Pawn scale in Pawn's database which matched your class without any spec.  This is what I expect to happen right now.  What is your expected behavior?

**Comment by Hendo72** [comment]
I would expect it to at least pick the right class...
![image](https://github.com/AlexFolland/AutoGear/assets/39675478/cce3fbe7-56a6-45c1-924e-e6a2289b081e)
This is a brand new Gnome Mage. It seems that it defaults to 'Warrior: Arms' for every new toon I create.

![image](https://github.com/AlexFolland/AutoGear/assets/39675478/8c06a99e-58e4-4c1d-98c9-bb327d3abe7e)
I was able to fix it by deleting the Warrior: Arms from the AutoGear file in the SavedVariables folder before you access the realm foders (see the pic below) and saving the file.

![image](https://github.com/AlexFolland/AutoGear/assets/39675478/e5a754cd-3a35-4db1-8187-72a2b411db35)

Now that I've done that, it's selecting the correct class now. I'll consider this problem solved.
