### ISSUE TITLE
Feature/Bug: Quiver's and Ammo pouches need a weight or an option to not be considered for AG (locked slot?)

### ISSUE THREAD

**Issue by cdmichaelb** [AlexFolland/AutoGear#56]
This might be a classic issue only, but quivers and ammo pouches give hunters attack speed, but they are weighted at 0, so normal bags replace them. Bag slots are currently not visible in the lock slots dropdown.

**Comment by AlexFolland** [comment]
I've checked the code and unless Blizzard changed something major, bag slots should be accounted for in the locked slots dropdown.  Can you please paste the output of `/dump AutoGearDB.LockedGearSlots`?

Also, can you please screenshot a tooltip of the quiver or ammo pouch that is being scored at 0?  There is code to score those, but maybe the string doesn't match.  I last tested this in WotLK Classic, so maybe something's different there.

**Comment by cdmichaelb** [comment]
> I've checked the code and unless Blizzard changed something major, bag slots should be accounted for in the locked slots dropdown. Can you please paste the output of /dump AutoGearDB.LockedGearSlots?

That was my mistake, I was unaware they changed the bag slots from 20-23 → 31-34.

Light Leather Quiver itemid 7278. I'm unsure if other quivers/ammo pouches are affected, since I don't have any.
![image](https://github.com/AlexFolland/AutoGear/assets/1451709/6c24dccd-ab4c-40b9-a158-f5cd1f727501)

**Comment by AlexFolland** [comment]
Thanks.

There is code in AutoGear to score bags based on slots alone, but only for bags with strings like "8 slot bag" or "8 slot enchanting bag", as long as it had "bag" in it.  There was no code for "quiver" or "ammo pouch".  I've added that locally, so at least these bags will be able to have their slots enumerated the next time I push a new version.

There was no code for "ranged attack speed" percentage like this.  I am guessing this benefit doesn't stack with other bags with the same benefit since that would be really dumb, so to implement this, I'd have to make AutoGear find the bag with the most ranged attack speed and equip only that one.  AutoGear is not set up for doing that right now.  I'll have to implement that when I have some more time and motivation.

**Comment by AlexFolland** [comment]
This might be fixed in the latest version which is not yet tagged for release.  Would you mind trying with the latest git master?

**Comment by AlexFolland** [comment]
I ended up releasing the latest version of the addon.  Would you mind testing the latest release?

**Comment by AlexFolland** [comment]
> Thanks.
> 
> There is code in AutoGear to score bags based on slots alone, but only for bags with strings like "8 slot bag" or "8 slot enchanting bag", as long as it had "bag" in it. There was no code for "quiver" or "ammo pouch". I've added that locally, so at least these bags will be able to have their slots enumerated the next time I push a new version.
> 
> There was no code for "ranged attack speed" percentage like this. I am guessing this benefit doesn't stack with other bags with the same benefit since that would be really dumb, so to implement this, I'd have to make AutoGear find the bag with the most ranged attack speed and equip only that one. AutoGear is not set up for doing that right now. I'll have to implement that when I have some more time and motivation.
> 
> It seems like that would also need to account for whether you have a bow or a gun, since a quiver would only work for arrows and an ammo pouch would only work for bullets. This complicates the situation further. Automatically choosing the right one would not be trivial to add in the current code. I'll have to think about how this should work.

Everything I've described in this comment is now in AutoGear.  I've been testing it on my own hunter in Classic SOD and it looks good to me, so I'm closing this issue for now.  Please feel free to comment here, reopen this ticket if this still isn't resolved, and/or create a new issue ticket if you encounter a new issue.
