### ISSUE TITLE
skinning knife

### ISSUE THREAD

**Issue by ncplus0** [AlexFolland/AutoGear#58]
wow clissic era SOD

its keepes traying to reclame the weapon i have for the skinning knife
i've nothice that it as value gear but on calculating it says zero insted of the correct score

![image](https://github.com/AlexFolland/AutoGear/assets/72767232/bc7bec05-6622-426c-9061-e4af116bc843)

**Comment by ncplus0** [comment]
![image](https://github.com/AlexFolland/AutoGear/assets/72767232/8a3442a9-467b-4fd8-92b9-8191c9bfc190)

**Comment by ELepianka1** [comment]
I'm getting the same issue but on regular classic era, not SoD.
![image](https://github.com/AlexFolland/AutoGear/assets/58861946/fd9bb3cd-a5e6-417d-a070-d73cfc0c07d0)

**Comment by AlexFolland** [comment]
This might be fixed in the latest version which is not yet tagged for release.  Would you mind trying with the latest git master?

**Comment by AlexFolland** [comment]
I ended up releasing the latest version of the addon.  Would you mind testing the latest release?

**Comment by ncplus0** [comment]
sorry for the delay i had surgery so i dint had time to test it, but now I’ve tried and looks 90% its fixed but only prob i notice is that in shaman we cannot use the spell to put buffs on the weapons and that must be taken in consideration when changing the weapon, but i dint test it yet, since must be done on a new made char

**Comment by ELepianka1** [comment]
played for a few hours this morning and it never tried to equip my skinning knife!

**Comment by AlexFolland** [comment]
Sounds fixed then.  Please feel free to open another ticket if there is a new issue.
