### ISSUE TITLE
soul bag

### ISSUE THREAD

**Issue by ncplus0** [AlexFolland/AutoGear#59]
hi mt8, when the request #56 was open o thought you would take care of the soul bags of warlock, but aparently i made a mistake.

can you please create an option so that the soul bags are not replace for normal bags.

![image](https://github.com/AlexFolland/AutoGear/assets/72767232/2f84100c-b0ca-423e-b84c-da0d311c9ee7)

 im actualy using a 12 slot bag and is trying to replace with a 10 bag

![image](https://github.com/AlexFolland/AutoGear/assets/72767232/193e2833-892a-4ff6-ace1-a01227f0714d)

tks in advance

**Comment by ncplus0** [comment]
i think its wasy, just update the score for 12 instade of zero

**Comment by AlexFolland** [comment]
I'm not sure how I feel about this.  I can't stand these limited bags which have their own empty slots that you can only put 1 type of thing in, personally.  I always use only generic bags on my warlocks, so my bag slots are more dynamic.  That makes the current behavior my preferred behavior.

I'll have to think about this a bit more and consider how to approach it in a way that preserves the current behavior and satisfies both kinds of users.

**Comment by AlexFolland** [comment]
I think the best way I will support this for now is with the slot-locking feature, meaning the ability to keep a soul bag on will depend on you locking the soul bag's equipment slot.  Any thoughts on that?

**Comment by AlexFolland** [comment]
This is supported via the slot-locking feature.  If that's not working, please comment and I'll reopen this.
