### ISSUE TITLE
Filter Blue/Equip on Classic WoW

### ISSUE THREAD

**Issue by Dastano** [AlexFolland/AutoGear#6]
Can you add a Option to not Equip BoE Epics/Blues that would be neat :)

**Comment by AlexFolland** [comment]
There's already an option for "Automatically confirm soul-binding".  Does disabling that do what you want?  If not, what's the difference?

**Comment by Dastano** [comment]
Well you often / sometimes get Green Gear which is better . So Auto-Soulbind is fine. But if you get a World-Drop Epic for example, it also equips it.

So that is what I asking for. To not equip Blues/Epics or a Option for both.

**Comment by AlexFolland** [comment]
I added options for this.  Thanks for the suggestion!
