### ISSUE TITLE
AutoGear.lua:3240: attempt to call method 'WrapTextInColorCode' (a nil value)

### ISSUE THREAD

**Issue by TyThompson** [AlexFolland/AutoGear#60]
Example when playing a rogue while it has stat weights for a paladin loaded it is generating this error.
I'm on Season of Discovery if that helps.

6x AutoGear/AutoGear.lua:3240: attempt to call method 'WrapTextInColorCode' (a nil value)
[string "@AutoGear/AutoGear.lua"]:3240: in function `AutoGearReadItemInfo'
[string "@AutoGear/AutoGear.lua"]:2570: in function `AutoGearUpdateEquippedItems'
[string "@AutoGear/AutoGear.lua"]:1821: in function <AutoGear/AutoGear.lua:1813>

Locals:
inventoryID = 16
lootRollID = nil
container = nil
slot = nil
questRewardIndex = nil
link = nil
info = <table> {
 isGear = true
 is1hWeaponOrOffHand = 1
 item = <table> {
 }
 YellowSockets = 0
 invType = 13
 link = "|cff1eff00|Hitem:12247::::::::50:::::::::|h[Broad Bladed Knife]|h|r"
 rarityColor = <table> {
 }
 numValidGearSlots = 0
 classID = 2
 BlueSockets = 0
 unusable = 1
 rarity = 2
 name = "Broad Bladed Knife"
 id = 12247
 RedSockets = 0
 subclassID = 15
 isWeaponOrOffHand = 1
 MetaSockets = 0
}
localizedClass = "Paladin"
class = "PALADIN"
spec = "Retribution"
(*temporary) = "(invalid item for "
(*temporary) = nil
(*temporary) = <table> {
 b = 0.730000
 colorStr = "fff48cba"
 g = 0.550000
 r = 0.960000
}
(*temporary) = "Retribution Paladin"
(*temporary) = "attempt to call method 'WrapTextInColorCode' (a nil value)"
futureAction = <table> {
}
L = <table> {
}
TOC_VERSION_CURRENT = 11502
TOC_VERSION_WOTLK = 30000
TOC_VERSION_WOD = 60000
weapons = "2h"
TOC_VERSION_MOP = 50000

**Comment by TyThompson** [comment]
It is working when I disable all other addons

I'll report back if I find the addon that is causing this

**Comment by AlexFolland** [comment]
Thanks for confirming.  This is not an AutoGear issue, so when you find the addon causing it, please report the issue to that addon's author.

**Comment by TyThompson** [comment]
RestedXP was the addon causing it

**Comment by TyThompson** [comment]
WeWantBlueShamans was causing the issue
https://www.curseforge.com/wow/addons/wewantblueshamans

**Comment by XiconQoo** [comment]
I am the author of https://www.curseforge.com/wow/addons/wewantblueshamans. Thanks for bringing up the issue. Since v1.06 I now create `ColorMixin`s with `CreateColor` (https://github.com/XiconQoo/WeWantBlueShamans/blob/main/core.lua#L65), thus this issue not being an issue anymore.
