### ISSUE TITLE
Update please

### ISSUE THREAD

**Issue by ollyvs** [AlexFolland/AutoGear#61]
Update please for Cataclysm Classic

**Comment by ollyvs** [comment]
Problem only in this function AutoGearGetClassAndSpec() i changed parameters manyally and everything else works
function AutoGearSetStatWeights()

	AutoGearItemInfoCache = {}

	local class, spec = AutoGearGetClassAndSpec()

	--print(class, spec)

	AutoGearCurrentWeighting = AutoGearDefaultWeights["ROGUE"]["Combat"] or nil

	weapons = AutoGearCurrentWeighting.weapons or "any"

	--AutoGearPrint("AutoGear: Stat weights set for \""..class..": "..spec.."\". Weapons: "..weapons, 3)

end

**Comment by AlexFolland** [comment]
I'm out of the country and not at my usual PC, so I don't have the access or the time right now to write and test an update, but I'd like to do so soon.  When I get back some time this month, I should be able to find some time to write and test an update.  In the mean time, if you do manage to solve it, please feel free to open a pull request and I'll review and merge it if it looks good.  Thanks for your interest!

**Comment by AlexFolland** [comment]
I would like to anticipate what changes will be needed by the time I'm available for solving this.  If anyone reading this has time, please install BugSack and BugGrabber, reproduce the error(s), and post the error(s) here, preferably in a collapsible monospace block.

**Comment by TyThompson** [comment]
Looks like realSpec is being evaluated to numbers and they don't seem to depend on the spec
Here are some examples
Warlock 865
Druid 748
Warrior 845
Rogue 181

**Comment by TyThompson** [comment]
Adding realSpec = tostring(realSpec) above

Line AutoGearPrint("AutoGear: Looks like you are a"..(realSpec:find("^[AEIOUaeiou]")....

Can solve the issue temporarily

**Comment by AlexFolland** [comment]
This should now be resolved.  Please test the latest head revision in the `master` branch in Cataclysm Classic and open a new ticket for any issue you reproduce.

**Comment by AlexFolland** [comment]
The addon is even more fixed now.  I made many changes.  Please check it out when you can.  By the way, thank you very much in particular for your contributions, @TyThompson.
