### ISSUE TITLE
Shadow damage in Classic

### ISSUE THREAD

**Issue by jamtur01** [AlexFolland/AutoGear#7]
I think AutoGear is assessing this wrong:

Here's it's logic:

<img width="324" alt="Screen Shot 2020-02-11 at 9 29 49 PM" src="https://user-images.githubusercontent.com/4365/74297756-d3209000-4d15-11ea-89a7-75cd98f7bacb.png">

And here are the items:

<img width="525" alt="Screen Shot 2020-02-11 at 9 30 02 PM" src="https://user-images.githubusercontent.com/4365/74297767-db78cb00-4d15-11ea-88b1-7e02b236976f.png">

It doesn't appear the Shadow damage is being taken into account?

**Comment by AlexFolland** [comment]
Yes, this does seem to be an issue.  Thanks for the pull request!  I've commented in it and requested @Synthetikaryote to review, since he usually handles the stat-related functionality in AutoGear.
