### ISSUE TITLE
Elemental shaman gear issue

### ISSUE THREAD

**Issue by tjesp** [AlexFolland/AutoGear#70]
I am playing on an elemental shaman.

I looked up shields on the auction house, but autogear said in the tooltip that elemental shaman's should not use shield!

Then I tried to look up staves and autogear said it was not valid weapon for a shaman.

Then what am I supposed to use?

**Comment by AlexFolland** [comment]
You must be using a spec override.  Elemental does not have `weapons` defined, which makes it use weapons type `any` with this line:

```Lua
weapons = AutoGearCurrentWeighting and (AutoGearCurrentWeighting.weapons or "any") or "any"
```

Please enter chat command `/ag spec` and show the output.

**Comment by AlexFolland** [comment]
I think this is not a real issue since it should only happen with a spec override.  Please let me know if this is still an issue and show the output of `/ag spec` and I'll reopen it.  Thanks for the report.
