### ISSUE TITLE
Undefined members (not working in SOD)

### ISSUE THREAD

**Issue by SGKalugerov** [AlexFolland/AutoGear#73]
Hello,
After the last patch in SOD,
`InterfaceOptionsFramePanelContainer`, `InterfaceOptions_AddCategory`, `InterfaceAddOnsList_Update` are undefined. I couldn't find anything by Blizzard regarding what they've changed.
This makes the addon unusable as of now.
Regards

**Comment by pacokeks** [comment]
Same issue here, many errors that pop up, tried finding a solution, but had no success

**Comment by AlexFolland** [comment]
I see this report.  Thank you for making it.  I haven't had any interest in playing WoW in the past few weeks, but I do plan to eventually come and fix this.  In the mean time, I would be happy to review a pull request that solves the issue.

**Comment by AlexFolland** [comment]
I logged into SoD after [my fix for Cataclysm Classic](https://github.com/AlexFolland/AutoGear/releases/tag/2024-10-31-release) and AutoGear seems to work, so I'm closing this.  If it doesn't work, please comment with the exact error(s) you're seeing from BugSack.
