### ISSUE TITLE
Autogear not working for new cata patch 4.4.1 

### ISSUE THREAD

**Issue by prot3ct** [AlexFolland/AutoGear#75]

**Comment by AlexFolland** [comment]
I see this report.  Thank you for making it. I haven't had any interest in playing WoW in the past several weeks, but I do plan to eventually come and fix this.  In the mean time, I would be happy to review a pull request that solves the issue.

By the way, when I do get around to fixing it, having information about it would be useful.  When making bug reports, please try to include error messages with debug information like stack traces.

**Comment by AlexFolland** [comment]
This is fixed in [2024-10-31-release](https://github.com/AlexFolland/AutoGear/releases/tag/2024-10-31-release).
