### ISSUE TITLE
Rogue: Off-Hand

### ISSUE THREAD

**Issue by tjesp** [AlexFolland/AutoGear#76]
If I use Pawn to evaluate in WoW Classic there is a Rogue: Mainspec scale as well as a "Rogue: Off-Hand" scale.

It could be nice if I could specify both somehow in Autogear.

I am not sure if there are other classes where this applies as well.

**Comment by AlexFolland** [comment]
This is not relevant to AutoGear.  Pawn evaluates the score of gear based on the "Off Hand" score by whether the item is labelled "Off Hand", and AutoGear gets the score directly from Pawn.  If you understand how that score is created, it's already working properly.  The score is from the gear type itself, not from the slot it's currently in.  You can see this in effect if you change the score for that gear type and see that it changes the score for any gear that is labelled "Off Hand", and doesn't change the score for any gear that's not labelled "Off Hand".

**Comment by AlexFolland** [comment]
Please let me know if what I've said is wrong and I'll reopen the issue.  I freely admit that I'm not always right.  Thank you for the report.
