### ISSUE TITLE
Not making scale comparisons with Pawn enabled

### ISSUE THREAD

**Issue by jamtur01** [AlexFolland/AutoGear#9]
With Pawn enabled I see this in a lot of item windows:

<img width="623" alt="Screen Shot 2020-06-21 at 2 17 24 PM" src="https://user-images.githubusercontent.com/4365/85232002-f47f4000-b3c9-11ea-88b0-8b3f2b7214a8.png">

See how the type of Rogue comparison isn't selected and hence there's no calculation - it'd normally say something like: `ROGUE1` and have a comparison value.

Also when Autogear starts I see:

<img width="318" alt="Screen Shot 2020-06-21 at 12 23 29 PM" src="https://user-images.githubusercontent.com/4365/85229893-82ebc580-b3ba-11ea-94b5-1903b6e3e8c5.png">

**Comment by AlexFolland** [comment]
Hmm, it looks like the author of Pawn must have changed something.  I haven't been playing WoW much lately and the version of Pawn I'm using stil works.  I wonder what version of Pawn broke it.  If you have time and the desire, would you mind tracking down the last version of Pawn that works with AutoGear for you?  If not, I probably won't get around to fixing this for a while since I have a full-time job and a newborn son these days.

**Comment by jamtur01** [comment]
What version of Pawn are you using? I've poked at the code a little and it seems like it's an intermittent fault, sometimes `PawnGetAllScalesEx()` returns the right data, and sometimes it doesn't. I wonder if there's some kind of initialization sequencing issue? I'll add some more debugging and see if I can't more consistently replicate it.

**Comment by AlexFolland** [comment]
AutoGear does call PawnIsReady() before querying Pawn I think, so if that returns true when Pawn isn't actually ready, that is probably a Pawn bug.  It's possible there's an AutoGear bug where it's doing something before getting true from PawnIsReady() though.  I'm so busy these days that I'm only typing these comments from my phone and haven't had time to sit down and look at this yet.  Thanks for looking at the code.  If you do get it working, I'd be very happy to review and accept a pull request.  So sorry about my unavailability.

**Comment by jamtur01** [comment]
No dramas on the availability. :) I am not sure what's happening - it's either startup sequencing or some kind of situation where Pawn sometimes doesn't return the spec correctly. You get "Rogue" but not the sub-spec. I'm going to pepper a bunch of debugging in the Pawn and scale functions to see if I can work out what's happening.

**Comment by AlexFolland** [comment]
Is this still happening?  It looks solved here, using TBC Classic and the latest version of Pawn.  Please let me know.

**Comment by jamtur01** [comment]
Looks fixed.

**Comment by jamtur01** [comment]
I just updated Pawn from Pawn-2.5.16 to Pawn-2.5.17 and the problem returned.

**Comment by AlexFolland** [comment]
I can't reproduce this with the latest alpha version of AutoGear that I released last night.  Is there an error?  What item is it?  What's your scale name?

**Comment by jamtur01** [comment]
Ah! I missed last night's release. Looks to be working now.

**Comment by AlexFolland** [comment]
I think this may be resolved now in the latest release since I moved DB initialization to the proper place (after PLAYER_ENTERING_WORLD).  Is it okay now?

**Comment by AlexFolland** [comment]
Oh, nice.  Thanks!
